spring:
  servlet:
    multipart:
      max-file-size: 200MB
      max-request-size: 200MB

cloudinary:
  cloud-name: ${CLOUDINARY_CLOUD_NAME:my-cloud-placeholder}
  api-key: ${CLOUDINARY_API_KEY:my-api-key-placeholder}
  api-secret: ${CLOUDINARY_API_SECRET:my-api-secret-placeholder}
